version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: scripts/
    destination: /home/ubuntu/quralyst-backend/scripts/
  - source: docker-compose.yml
    destination: /home/ubuntu/quralyst-backend/
  - source: imageDetail.json
    destination: /home/ubuntu/quralyst-backend/

permissions:
  - object: /home/ubuntu/quralyst-backend/scripts/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 120
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
